# festivals-identity-server configuration file v1.0
# TOML 1.0.0-rc.2+

[service]
bind-address = "localhost"
port = 22580
key = "TEST_API_KEY_001"

[database]
host = "localhost"
port = 3306
username = "festivals.identity.writer"
password = "we4711"
database-name = "festivals_identity_database"

[heartbeat]
endpoint = "localhost"

[jwt]
expiration = 1000
accessprivatekeypath = "./access-private.pem"
accesspublickeypath = "./access-public.pem"
refreshprivatekeypath = "./refresh-private.pem"
refreshpublickeypath = "./refresh-public.pem"