# festivals-identity-server configuration file v1.0
# TOML 1.0.0-rc.2+

[service]
bind-address = "localhost"
bind-host = "localhost"
port = 22580
key = "TEST_API_KEY_001"

[tls]
festivaslapp-root-ca = "/usr/local/festivals-identity-server/ca.crt"
cert = "/usr/local/festivals-identity-server/server.crt"
key = "/usr/local/festivals-identity-server/server.key"

[database]
host = "localhost"
port = 3306
username = "festivals.identity.writer"
password = "we4711"
festivalsapp-root-ca = "/usr/local/festivals-identity-server/ca.crt"
cert = "/usr/local/festivals-identity-server/database-client.crt"
key = "/usr/local/festivals-identity-server/database-client.key"

[heartbeat]
endpoint = "localhost"
interval = 6

[jwt]
expiration = 180
accessprivatekeypath = "./access-private.pem"
accesspublickeypath = "./access-public.pem"